version: '3.8'

services:
  app:
    image: 'tbell-mm-backend:latest'
    build: .
    env_file:
      - ".env"
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    container_name: tbell-mm-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:${MYSQLDB_PORT}/${MYSQLDB_DATABASE}?useSSL=false
      - SPRING_DATASOURCE_USERNAME=${MYSQLDB_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - SPRING_JPA_PROPERTIES.HIBERNATE.DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - TZ=Asia/Seoul
      - _JAVA_OPTIONS=-Xmx15g
    volumes:
      - ./log:/app/log
    networks:
      mm-network:

  db:
    container_name: tbell-mm-mysql
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_PORT}:${MYSQLDB_PORT}
    volumes:
      - mysqldb-volume:/var/lib/mysql
      - ./bak:/var/lib/backup
    networks:
      mm-network:

  backup:
    image: mysql:5.7
    container_name: tbell-mm-mysql-backup
    env_file:
      - ".env"
    depends_on:
      - db
    volumes:
      - ./bak:/var/lib/backup
    command: >
      bash -c "
      while true; do
        sleep 60
        mysqldump -h mysqldb -u$$MYSQLDB_USER -p$$MYSQLDB_ROOT_PASSWORD $$MYSQLDB_DATABASE > /var/lib/backup/$$(date +%Y-%m-%d-%H-%M-%S).sql
        echo ""Backup done at $$(date +%Y-%m-%d_%H:%M:%S)""
        sleep 14400
      done
      "
    environment:
      MYSQLDB_USER: ${MYSQLDB_USER}
      MYSQLDB_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQLDB_DATABASE: ${MYSQLDB_DATABASE}
      TZ: Asia/Seoul
    networks:
      mm-network:

volumes:
  mysqldb-volume:

networks:
  mm-network:
    driver: bridge