spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
  datasource:
#    url: jdbc:postgresql://14.36.253.130:5432/sync
#    username: "postgres"
#    password: "postgres"
#    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
#  profiles:
#    active: @activatedProperties@


logging:
  level:
    root: info
#    com.zaxxer.hikari.HikariConfig: info
#    com.zaxxer.hikari: TRACE
  file:
    path: /app/log/
    name: /app/log/app.log

server:
  port: 9090
  servlet:
    context-path: /mm

